# Generated by Django 3.1.4 on 2021-07-19 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('number_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('role', models.CharField(blank=True, choices=[('manager', 'Менеджер'), ('patient', 'Пациент')], max_length=40, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='patients_picture')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('archive', models.BooleanField(blank=True, default=False, null=True, verbose_name='Архив')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='app.baseprofile')),
            ],
            options={
                'verbose_name': 'Профиль пациента',
                'verbose_name_plural': 'Профили пациентов',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='managers_picture')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='app.baseprofile')),
            ],
            options={
                'verbose_name': 'Профиль менеджера',
                'verbose_name_plural': 'Профили менеджеров',
            },
        ),
    ]
