# Generated by Django 3.1.4 on 2021-07-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseprofile',
            options={'verbose_name': 'Основной профиль', 'verbose_name_plural': 'Основные профиля'},
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='number_phone',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='manager',
            name='number_phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
