# Generated by Django 3.1.7 on 2021-07-20 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210720_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccompanyingIllnesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Сопутсвуещие заболевание',
                'verbose_name_plural': 'Сопутсвующие заболевания',
            },
        ),
        migrations.CreateModel(
            name='BadHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Вредная привычка',
                'verbose_name_plural': 'Вредные привычки',
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('urination_frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeregistrationCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Причина снятия',
                'verbose_name_plural': 'Причины снятия',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('patronymic', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+'), ('1-', '1-'), ('2-', '2-'), ('3-', '3-'), ('4-', '4-')], max_length=250, null=True)),
                ('comments', models.TextField()),
                ('bad_habits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.badhabits')),
            ],
            options={
                'verbose_name': 'Отец',
                'verbose_name_plural': 'Отцы',
            },
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
        migrations.CreateModel(
            name='PastIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Перенесенное заболевание',
                'verbose_name_plural': 'Перенесенные заболевания',
            },
        ),
        migrations.CreateModel(
            name='PMSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'ПМСП',
                'verbose_name_plural': 'ПМСП',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Отчество')),
                ('number_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Мобильный')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Менеджер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='RiskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Группа риска',
                'verbose_name_plural': 'Группы риска',
            },
        ),
        migrations.CreateModel(
            name='Wellbeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Самочувствие',
                'verbose_name_plural': 'Самочувствие',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
            },
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile',
        ),
        migrations.AddField(
            model_name='patient',
            name='IIN',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+'), ('1-', '1-'), ('2-', '2-'), ('3-', '3-'), ('4-', '4-')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='children_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество детей'),
        ),
        migrations.AddField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deregistration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_menstruation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_pregnancies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='BaseProfile',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='checklist',
            name='medications',
            field=models.ManyToManyField(to='app.Medications'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wellbeing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wellbeing', verbose_name='Самочувствие'),
        ),
        migrations.AddField(
            model_name='patient',
            name='PMSP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pmsp'),
        ),
        migrations.AddField(
            model_name='patient',
            name='accompanying_illnesses',
            field=models.ManyToManyField(to='app.AccompanyingIllnesses', verbose_name='Сопутсвующие заболевания'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bad_habits',
            field=models.ManyToManyField(blank=True, null=True, to='app.BadHabits', verbose_name='Плохие привычки'),
        ),
        migrations.AddField(
            model_name='patient',
            name='deregistration_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.deregistrationcause'),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.district'),
        ),
        migrations.AddField(
            model_name='patient',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.father', verbose_name='Отец'),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_illnesses',
            field=models.ManyToManyField(to='app.PastIllness', verbose_name='Перенесенные заболевания'),
        ),
        migrations.AddField(
            model_name='patient',
            name='risk_group',
            field=models.ManyToManyField(blank=True, null=True, to='app.RiskGroup', verbose_name='Группа риска'),
        ),
        migrations.AddField(
            model_name='patient',
            name='work_type',
            field=models.ManyToManyField(blank=True, null=True, to='app.WorkType'),
        ),
    ]
