# Generated by Django 3.1.7 on 2021-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210720_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Чек лист', 'verbose_name_plural': 'Чек листы'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='accompanying_illnesses',
            field=models.ManyToManyField(blank=True, null=True, to='app.AccompanyingIllnesses', verbose_name='Сопутсвующие заболевания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_illnesses',
            field=models.ManyToManyField(blank=True, null=True, to='app.PastIllness', verbose_name='Перенесенные заболевания'),
        ),
    ]
