# Generated by Django 3.1.7 on 2021-07-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210720_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
