# Generated by Django 3.1.7 on 2021-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210720_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_phone',
            field=models.CharField(default='', max_length=250, verbose_name='Мобильный телефон'),
        ),
    ]
