# Generated by Django 3.1.7 on 2021-07-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210720_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='IIN',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='before_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='children_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_pregnancies',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
