# Generated by Django 3.1.4 on 2021-07-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210720_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Опасный признак',
                'verbose_name_plural': 'Опасные признаки',
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='dangerous_signs',
            field=models.ManyToManyField(blank=True, null=True, to='app.DangerousSigns'),
        ),
    ]
