# Generated by Django 3.1.7 on 2021-07-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210721_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='urination_frequency',
            new_name='urinary_frequency',
        ),
        migrations.AddField(
            model_name='checklist',
            name='ambulance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='breast_feeding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='constipation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='domestic_violence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='emotion_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='planned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='profilactic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='signs_urinary_infections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist',
            name='transposrt',
            field=models.BooleanField(default=False),
        ),
    ]
