# Generated by Django 3.1.7 on 2021-07-22 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_checklist_complaints_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='medications',
            field=models.ManyToManyField(blank=True, null=True, to='app.Medications'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='urinary_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='wellbeing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wellbeing', verbose_name='Самочувствие'),
        ),
    ]
