# Generated by Django 3.1.7 on 2021-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210722_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='before_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='children_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_pregnancies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
