# Generated by Django 3.1.7 on 2021-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210722_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
