# Generated by Django 3.1.7 on 2021-07-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210722_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='father',
            name='bad_habits',
        ),
        migrations.AddField(
            model_name='father',
            name='bad_habits',
            field=models.ManyToManyField(blank=True, null=True, to='app.BadHabits', verbose_name='Плохие привычки'),
        ),
    ]
