# Generated by Django 3.1.4 on 2021-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210723_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
