# Generated by Django 3.1.4 on 2021-07-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210723_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='before_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
